defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: default

title: Sustainable Development
subtitle: hyh1016의 개발 일지

# left_side:
#   background_image: "./assets/images/left-background.jpg"
#   background_color: "#F00"
#   close_button_color: "#F00"
#   text_color: "#F00"

footer:
  copyright_text: "&copy; Yihyun Ha"

# Side Menu Links
menu:
  - text: Portfolio
    link: /
    icon: ""

  - text: Skills & Offers
    link: /skills-and-offers
    icon: ""

  - text: Contact Me
    link: /contact
    icon: ""

  - text: My Resume
    link: /resume
    icon: ""

  - text: Blog Posts
    link: /posts
    icon: ""

# Socialmedia Icons
social_icons:

  - name: github
    link: https://github.com/hyh1016
    icon: fab fa-github-square

  - name: facebook
    link: https://www.facebook.com/hyh1016
    icon: fab fa-facebook-square

    
